import { useEffect, useMemo, useState } from "react";
import { loadCatalog, loadSource } from "./api";
import type { CatalogEntry, CatalogResponse } from "./types";

export function FunctionCatalog() {
  const [data,setData]=useState<CatalogResponse|null>(null),[query,setQuery]=useState(""),[stage,setStage]=useState("all"),[status,setStatus]=useState("all"),[criticality,setCriticality]=useState("all"),[tested,setTested]=useState(false),[blocked,setBlocked]=useState(false);
  const [selected,setSelected]=useState<CatalogEntry|null>(null),[source,setSource]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[sourceLoading,setSourceLoading]=useState(false);
  useEffect(()=>{const c=new AbortController();loadCatalog(c.signal).then(x=>{setData(x);setSelected(x.entries[0]??null)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:"Каталог недоступен")});return()=>c.abort()},[]);
  const entries=useMemo(()=>data?.entries.filter(x=>(stage==="all"||x.stage===stage)&&(status==="all"||x.status===status)&&(criticality==="all"||x.criticality===criticality)&&(!tested||x.test_count>0)&&(!blocked||Boolean(x.blocker&&!x.blocker.includes("NO BLOCKER")))&&`${x.title} ${x.technical_name} ${x.description}`.toLowerCase().includes(query.toLowerCase()))??[],[data,query,stage,status,criticality,tested,blocked]);
  const visibleEntries=useMemo(()=>entries.slice(0,250),[entries]);
  async function showSource(entry:CatalogEntry){setSelected(entry);setSource(null);setSourceLoading(true);try{setSource((await loadSource(entry.source_path,entry.line_start,entry.line_end)).content)}catch(e){setSource(e instanceof Error?e.message:"Source недоступен")}finally{setSourceLoading(false)}}
  return <section className="catalog-section" aria-labelledby="catalog-title"><div className="catalog-head"><div><p className="eyebrow">Понятный каталог</p><h2 id="catalog-title">Функции проекта</h2><p>Назначение — крупно; техническое имя — серой подписью.</p></div>{data&&<div className="catalog-stats"><b>{data.summary.functions}</b><span>функций</span><b>{data.summary.tests}</b><span>тестов</span></div>}</div>{error&&<p className="reason">{error}</p>}
  <div className="catalog-tools"><input aria-label="Поиск функций" placeholder="Найти функцию или проблему…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">Все этапы</option>{["stage1","stage2","stage2b","stage3","test_module","shared"].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Все статусы</option>{["complete","closed","need_testing","in_progress","deprecated","discovered"].map(x=><option key={x}>{x}</option>)}</select><select value={criticality} onChange={e=>setCriticality(e.target.value)}><option value="all">Любая важность</option><option value="critical">Критические</option><option value="normal">Обычные</option></select><label><input type="checkbox" checked={tested} onChange={e=>setTested(e.target.checked)}/>есть тест</label><label><input type="checkbox" checked={blocked} onChange={e=>setBlocked(e.target.checked)}/>есть blocker</label></div>
  {entries.length>visibleEntries.length&&<p className="reason">Показаны первые {visibleEntries.length} из {entries.length} — уточните фильтры или поиск.</p>}
  <div className="catalog-layout"><div className="function-list" role="list">{visibleEntries.length===0&&<p className="catalog-list-empty">Ничего не найдено — измените фильтры или запрос поиска.</p>}{visibleEntries.map(x=><button role="listitem" className={selected?.id===x.id?"selected":""} onClick={()=>{setSelected(x);setSource(null)}} key={x.id}><span><b>{x.title}</b><small>{x.technical_name} · {x.source_path}:{x.line_start}</small></span><i className={`status-chip ${x.status}`}>{x.status}</i></button>)}</div><aside className="function-inspector">{selected?<><p className="eyebrow">Простыми словами</p><h3>{selected.title}</h3><p>{selected.description}</p><h4>Почему важно</h4><p>{selected.why_important}</p><h4>Если работает неверно</h4><p>{selected.failure_impact}</p><dl><div><dt>Статус</dt><dd>{selected.status}</dd></div><div><dt>Тестовые связи</dt><dd>{selected.test_count}</dd></div><div><dt>Приоритет задачи</dt><dd>{selected.task_priority??"готово"}</dd></div></dl><details><summary>Техническая информация</summary><code>{selected.id}</code><code>{selected.source_path}:{selected.line_start}-{selected.line_end}</code></details><button className="source-button" disabled={sourceLoading} onClick={()=>showSource(selected)}>{sourceLoading?"Загрузка…":"Показать исходный код · только чтение"}</button>{source&&<pre className="source-preview">{source}</pre>}</>:<p>Выберите функцию.</p>}</aside></div></section>;
}
