import {useEffect,useState} from "react";
import ReactFlow,{Background,Controls,Handle,MiniMap,Panel,Position,useEdgesState,useNodesState,useReactFlow} from "@xyflow/react";
import ELK from "elkjs/lib/elk.bundled.js";
import "@xyflow/react/dist/style.css";
import type {CanvasGraph,CanvasNodeData} from "./types";
import {loadCanvas,loadReadiness} from "./api";
import type {ReadinessItem} from "./types";
const elk=new ELK();
function PipelineNode({data}:{data:CanvasNodeData}){return <div className={`pipeline-node ${data.kind} status-${data.status}`} tabIndex={0} aria-label={`${data.kind}: ${data.title}; статус ${data.status}`}><Handle type="target" position={Position.Left}/><b>{data.title}</b><small>{data.technical_name}</small><span>{data.status}</span>{data.badges.map(x=><i key={x}>{x}</i>)}<Handle type="source" position={Position.Right}/></div>}
const nodeTypes={pipeline:PipelineNode};
const DIM_LABELS:[string,string][]=[["implementation","Implementation"],["unit","Unit tests"],["synthetic","Synthetic"],["real_photo","Real photos"],["calibration","Calibration"]];
function DimBars({dims}:{dims:{name:string;state:string;reason:string}[]}){return <div className="dim-bars">{DIM_LABELS.map(([key,label])=>{const d=dims.find(x=>x.name===key);const st=d?.state??'unknown';return <div className="dim-row" key={key} title={d?.reason??'Нет подтверждённого источника.'}><span className="dim-label">{label}</span><div className="dim-bar"><div className={`dim-bar-fill state-${st}`}/></div><small className={`dim-state state-${st}`}>{st==='passed'?'подтверждено':st==='failed'?'провалено':'нет данных'}</small></div>})}</div>}
async function elkLayout(nodes:any[],edges:any[]){const graph=await elk.layout({id:'root',layoutOptions:{'elk.algorithm':'layered','elk.direction':'RIGHT','elk.spacing.nodeNode':'38','elk.layered.spacing.nodeNodeBetweenLayers':'90'},children:nodes.map(n=>({id:n.id,width:240,height:n.data.kind==='stage'?88:72})),edges:edges.map(e=>({id:e.id,sources:[e.source],targets:[e.target]}))});const pos=new Map((graph.children??[]).map(n=>[n.id,{x:n.x??0,y:n.y??0}]));return nodes.map(n=>({...n,position:pos.get(n.id)??n.position}))}
export function PipelineCanvas(){
 const [graph,setGraph]=useState<CanvasGraph|null>(null),[readiness,setReadiness]=useState<ReadinessItem[]>([]),[selected,setSelected]=useState<string|null>(null),[preset,setPreset]=useState('Full'),[query,setQuery]=useState(''),[zoom,setZoom]=useState(1),[error,setError]=useState('');
 const [nodes,setNodes,onNodesChange]=useNodesState<any>([]),[edges,setEdges,onEdgesChange]=useEdgesState<any>([]);const rf=useReactFlow();
 useEffect(()=>{Promise.all([loadCanvas(),loadReadiness()]).then(([g,r])=>{setGraph(g);setReadiness(r)}).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(!graph)return;const allowed=new Set(graph.presets[preset]??graph.presets.Full);const q=query.toLowerCase();const ns=graph.nodes.filter(n=>allowed.has(n.id)&&(!q||`${n.title} ${n.technical_name}`.toLowerCase().includes(q))).map(n=>({id:n.id,type:'pipeline',position:{x:n.x,y:n.y},data:n,hidden:zoom<.28&&n.kind!=='stage'||zoom<.5&&n.kind==='function'}));const ids=new Set(ns.map(n=>n.id));const es=graph.edges.filter(e=>ids.has(e.source)&&ids.has(e.target)&&e.label!=='contains').map(e=>({id:e.id,source:e.source,target:e.target,label:e.confidence.startsWith('heuristic')?'?':undefined,animated:e.confidence==='runtime_observed',className:`edge-${e.confidence}`}));elkLayout(ns,es).then(x=>{setNodes(x);setEdges(es);setTimeout(()=>rf.fitView({padding:.12}),0)}).catch(e=>setError(String(e)))},[graph,preset,query,zoom]);
 const loading=!graph&&!error;
 return <section className="pipeline-canvas"><div className="canvas-toolbar"><input placeholder="Найти функцию…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Поиск узла"/>{graph&&Object.keys(graph.presets).map(x=><button className={preset===x?'active':''} onClick={()=>setPreset(x)} key={x}>{x}</button>)}</div>
 {error&&<p className="canvas-error">{error}</p>}
 {loading&&<p className="canvas-loading">Загрузка карты проекта…</p>}
 <div className="canvas-surface"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeClick={(_,n)=>setSelected(String(n.data.technical_name))} onMove={(_,v)=>setZoom(v.zoom)} fitView colorMode="dark" minZoom={.08} maxZoom={2}><Background gap={22} size={1}/><MiniMap pannable zoomable nodeColor={n=>n.data.status==='complete'?'#287a52':n.data.criticality==='critical'?'#9b4b45':'#34465d'}/><Controls/><Panel position="top-right">{graph?.summary.nodes} nodes · semantic zoom</Panel>{selected&&(()=>{const r=readiness.find(x=>x.function_id===selected);return r?<Panel position="bottom-right"><aside className="readiness-card"><b>{r.status}</b><small>{r.policy}</small><p>{r.explanation}</p><DimBars dims={r.dimensions}/><span>Не закрыто: {r.missing.join(', ')||'нет'}</span>{r.blocked_by.length>0&&<span>Заблокировано: {r.blocked_by.join(', ')}</span>}</aside></Panel>:null})()}</ReactFlow></div></section>}
