import type { TrackDescriptor, TrackKind } from '../types/timeline';

/**
 * Track definitions for the timeline.
 * Each track represents a layer of data visualization.
 */

export const TRACK_COLORS: Record<TrackKind, string> = {
  quality: 'var(--metric-quality)',
  texture: 'var(--metric-texture)',
  geometry: 'var(--metric-geometry)',
  pca: 'var(--metric-geometry)',
  calibration: 'var(--metric-calibration)',
  pose: 'var(--metric-pose)',
  chronology: 'var(--metric-chronology)',
  ldm_difference: 'var(--metric-anomaly)',
  anomaly: 'var(--metric-anomaly)',
  photo: 'var(--color-neutral)',
};

export const TRACK_DEFINITIONS: TrackDescriptor[] = [
  {
    id: 'quality',
    kind: 'quality',
    label: 'КАЧЕСТВО',
    color: TRACK_COLORS.quality,
    visible: true,
    height: 60,
    dataKey: 'quality',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'alignmentQuality',
    kind: 'quality',
    label: 'ВЫРАВНИВАНИЕ',
    color: 'var(--metric-quality)',
    visible: true,
    height: 50,
    dataKey: 'alignmentQuality',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'skinAuthenticity',
    kind: 'texture',
    label: 'АУТЕНТИЧНОСТЬ КОЖИ',
    color: TRACK_COLORS.texture,
    visible: true,
    height: 60,
    dataKey: 'skinAuthenticity',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'siliconeProb',
    kind: 'texture',
    label: 'ПРИЗНАК СИЛИКОНА',
    color: 'var(--color-synthetic)',
    visible: true,
    height: 50,
    dataKey: 'siliconeProb',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'skinQuality',
    kind: 'texture',
    label: 'КАЧЕСТВО КОЖИ',
    color: TRACK_COLORS.texture,
    visible: false,
    height: 50,
    dataKey: 'skinQuality',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'wrinkleDensity',
    kind: 'texture',
    label: 'ПЛОТНОСТЬ МОЩИН',
    color: 'var(--metric-texture)',
    visible: false,
    height: 50,
    dataKey: 'wrinkleDensity',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'boneScore',
    kind: 'geometry',
    label: 'КОСТНАЯ ОСНОВА',
    color: TRACK_COLORS.geometry,
    visible: true,
    height: 60,
    dataKey: 'boneScore',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'symmetry',
    kind: 'geometry',
    label: 'СИММЕТРИЯ',
    color: 'var(--metric-geometry)',
    visible: true,
    height: 50,
    dataKey: 'symmetry',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'orbit',
    kind: 'geometry',
    label: 'ГЛАЗНИЦА',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'orbit',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'chin',
    kind: 'geometry',
    label: 'ПОДБОРОДОК',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'chin',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'jaw',
    kind: 'geometry',
    label: 'ЧЕЛЮСТЬ',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'jaw',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'cheek',
    kind: 'geometry',
    label: 'СКУЛА',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'cheek',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'p0',
    kind: 'pca',
    label: 'PC 0 · ФОРМА',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'p0',
    domain: null,
    unit: null,
  },
  {
    id: 'p1',
    kind: 'pca',
    label: 'PC 1 · ФОРМА',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'p1',
    domain: null,
    unit: null,
  },
  {
    id: 'p2',
    kind: 'pca',
    label: 'PC 2 · ФОРМА',
    color: 'var(--metric-geometry)',
    visible: false,
    height: 50,
    dataKey: 'p2',
    domain: null,
    unit: null,
  },
  {
    id: 'zOrbitDepth',
    kind: 'calibration',
    label: 'Z · ГЛУБИНА ГЛАЗНИЦЫ',
    color: TRACK_COLORS.calibration,
    visible: false,
    height: 50,
    dataKey: 'zOrbitDepth',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'zChinProj',
    kind: 'calibration',
    label: 'Z · ВЫСТУП ПОДБОРОДКА',
    color: 'var(--metric-calibration)',
    visible: false,
    height: 50,
    dataKey: 'zChinProj',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'zJawWidth',
    kind: 'calibration',
    label: 'Z · ШИРИНА ЧЕЛЮСТИ',
    color: 'var(--metric-calibration)',
    visible: false,
    height: 50,
    dataKey: 'zJawWidth',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'zCheek',
    kind: 'calibration',
    label: 'Z · СКУЛА',
    color: 'var(--metric-calibration)',
    visible: false,
    height: 50,
    dataKey: 'zCheek',
    domain: null,
    unit: 'σ',
  },
  {
    id: 'yaw',
    kind: 'pose',
    label: 'YAW · ПОВОРОТ',
    color: TRACK_COLORS.pose,
    visible: false,
    height: 50,
    dataKey: 'yaw',
    domain: [-90, 90],
    unit: '°',
  },
  {
    id: 'pitch',
    kind: 'pose',
    label: 'PITCH · НАКЛОН',
    color: 'var(--metric-pose)',
    visible: false,
    height: 50,
    dataKey: 'pitch',
    domain: [-45, 45],
    unit: '°',
  },
  {
    id: 'roll',
    kind: 'pose',
    label: 'ROLL · КРЕН',
    color: 'var(--metric-pose)',
    visible: false,
    height: 50,
    dataKey: 'roll',
    domain: [-45, 45],
    unit: '°',
  },
  {
    id: 'residualYaw',
    kind: 'pose',
    label: 'ОСТАТОЧНЫЙ YAW',
    color: 'var(--metric-pose)',
    visible: false,
    height: 50,
    dataKey: 'residualYaw',
    domain: [-30, 30],
    unit: '°',
  },
  {
    id: 'expressionMagnitude',
    kind: 'chronology',
    label: 'ВЕЛИЧИНА ВЫРАЖЕНИЯ',
    color: TRACK_COLORS.chronology,
    visible: false,
    height: 50,
    dataKey: 'expressionMagnitude',
    domain: null,
    unit: null,
  },
  {
    id: 'jawOpenDegree',
    kind: 'chronology',
    label: 'ОТКРЫТИЕ РТА',
    color: 'var(--metric-chronology)',
    visible: false,
    height: 50,
    dataKey: 'jawOpenDegree',
    domain: [0, 40],
    unit: '°',
  },
  {
    id: 'visualAge',
    kind: 'chronology',
    label: 'ВИЗУАЛЬНЫЙ ВОЗРАСТ',
    color: 'var(--metric-chronology)',
    visible: false,
    height: 50,
    dataKey: 'visualAge',
    domain: null,
    unit: 'лет',
  },
  {
    id: 'calendarAge',
    kind: 'chronology',
    label: 'КАЛЕНДАРНЫЙ ВОЗРАСТ',
    color: 'var(--metric-chronology)',
    visible: false,
    height: 50,
    dataKey: 'calendarAge',
    domain: null,
    unit: 'лет',
  },
  {
    id: 'ldmShapeDifference',
    kind: 'ldm_difference',
    label: 'РАЗЛИЧИЕ ФОРМЫ (LDM)',
    color: TRACK_COLORS.ldm_difference,
    visible: true,
    height: 70,
    dataKey: 'ldmShapeDifference',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'ldm106Difference',
    kind: 'ldm_difference',
    label: 'LDM106 · РАЗЛИЧИЕ',
    color: 'var(--color-warning)',
    visible: false,
    height: 50,
    dataKey: 'ldm106Difference',
    domain: [0, 1],
    unit: null,
  },
  {
    id: 'ldm134Difference',
    kind: 'ldm_difference',
    label: 'LDM134 · РАЗЛИЧИЕ',
    color: 'var(--color-warning)',
    visible: false,
    height: 50,
    dataKey: 'ldm134Difference',
    domain: [0, 1],
    unit: null,
  },
];

export function getTrackById(id: string): TrackDescriptor | undefined {
  return TRACK_DEFINITIONS.find((t) => t.id === id);
}

export function getVisibleTracks(): TrackDescriptor[] {
  return TRACK_DEFINITIONS.filter((t) => t.visible);
}

export function getTracksByKind(kind: TrackKind): TrackDescriptor[] {
  return TRACK_DEFINITIONS.filter((t) => t.kind === kind);
}
