import { useMemo } from "react";
import { ERA_META, FUZZY_COLORS, HYPOTHESIS_COLORS, POSE_BUCKETS, POSE_LABELS, type Era, type Photo } from "../data";

type Kind = "MATRIX" | "COMPARE" | "INSPECTOR" | "DRIFT" | "METRICS" | "STATS";
interface Props { kind: Kind; photos: Photo[]; selected: Photo | null; onSelect: (id: string) => void; onInspect: (photo: Photo) => void; onCompare: () => void; }

const mean = (rows: Photo[], pick: (photo: Photo) => number) => rows.length ? rows.reduce((sum, row) => sum + pick(row), 0) / rows.length : 0;
const anomaly = (p: Photo) => !["CONSISTENT", "STRONGLY_MATCHING"].includes(p.fuzzy);

function Shell({ title, sub, children }: { title: string; sub: string; children: React.ReactNode }) {
  return <section className="h-full overflow-auto bg-bg p-5 scanlines"><header className="mb-5"><h1 className="font-display text-xl tracking-forensic">{title}</h1><p className="font-mono text-[10px] text-text-muted mt-1">{sub}</p></header>{children}</section>;
}

function MetricCard({ label, value, note, color = "#5591c7" }: { label: string; value: string; note: string; color?: string }) {
  return <article className="bg-surface border border-border p-3 min-h-24"><div className="font-mono text-[9px] tracking-forensic text-text-muted">{label}</div><div className="font-display text-2xl mt-2" style={{ color }}>{value}</div><div className="font-mono text-[9px] text-text-faint mt-2">{note}</div></article>;
}

function Spark({ values, color = "#5591c7", height = 120 }: { values: number[]; color?: string; height?: number }) {
  const min = Math.min(...values), max = Math.max(...values), span = max - min || 1;
  const points = values.map((v, i) => `${(i / Math.max(1, values.length - 1)) * 100},${height - 8 - ((v - min) / span) * (height - 16)}`).join(" ");
  return <svg viewBox={`0 0 100 ${height}`} preserveAspectRatio="none" className="w-full" style={{ height }} aria-label="График метрики"><path d={`M0 ${height - 8} H100`} stroke="rgba(255,255,255,.08)" /><polyline points={points} fill="none" stroke={color} strokeWidth="1.2" vectorEffect="non-scaling-stroke" /></svg>;
}

export default function AnalysisViews({ kind, photos, selected, onSelect, onInspect, onCompare }: Props) {
  const sampled = useMemo(() => photos.filter((_, i) => i % Math.max(1, Math.floor(photos.length / 120)) === 0).slice(0, 120), [photos]);
  const eras = Object.keys(ERA_META) as Era[];

  if (kind === "MATRIX") return <Shell title="МАТРИЦА ЭПОХ × РАКУРСОВ" sub="Сравнение проводится только внутри совместимых pose bins; пустые ячейки не интерполируются."><div className="overflow-auto border border-border"><table className="w-full min-w-[980px] border-collapse font-mono text-[10px]"><thead><tr><th className="sticky left-0 bg-surface p-2 text-left">ЭПОХА</th>{POSE_BUCKETS.map(p => <th key={p} className="bg-surface p-2 text-text-muted">{POSE_LABELS[p]}</th>)}</tr></thead><tbody>{eras.map(era => <tr key={era}><th className="sticky left-0 bg-surface p-2 text-left" style={{ color: ERA_META[era].color }}>{ERA_META[era].label}</th>{POSE_BUCKETS.map(pose => { const rows = photos.filter(p => p.era === era && p.bucket === pose); const score = mean(rows, p => p.boneScore); return <td key={pose} className="border border-border p-2 text-center" title={`${rows.length} фото`}><div className="text-base">{rows.length ? score.toFixed(3) : "—"}</div><div className="text-text-faint">n={rows.length}</div></td>; })}</tr>)}</tbody></table></div></Shell>;

  if (kind === "COMPARE") return <Shell title="СРАВНЕНИЕ ДИАПАЗОНОВ" sub="Выделите диапазоны A и B на таймлайне. Пороговые решения отображаются как evidence status, а не как вердикт личности."><div className="grid grid-cols-3 gap-3"><MetricCard label="ВЫБРАНО A" value="SHIFT+DRAG" note="Первый диапазон" /><MetricCard label="ВЫБРАНО B" value="SHIFT+DRAG" note="Второй диапазон" /><button onClick={onCompare} className="bg-info/20 border border-info/50 p-4 text-left hover:bg-info/30"><div className="font-mono text-[9px]">ОТКРЫТЬ ПАНЕЛЬ</div><div className="font-display text-xl mt-2">COMPARE</div></button></div><div className="mt-5 bg-surface border border-border p-4"><Spark values={sampled.map(p => p.boneScore)} /><div className="font-mono text-[9px] text-text-muted">Костный индекс по текущей выборке · A/B вычисляются после выделения</div></div></Shell>;

  if (kind === "INSPECTOR") { const photo = selected ?? photos[0]; return <Shell title="3D / BFM INSPECTOR" sub="3DDFA-V3-ready: mesh, 106/134 landmarks, point-to-plane heatmap, morph и экспорт измерений."><div className="grid grid-cols-[minmax(0,1fr)_300px] gap-4"><div className="min-h-[520px] bg-surface border border-border relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(85,145,199,.22),transparent_62%)]" /><svg viewBox="0 0 600 520" className="absolute inset-0 w-full h-full"><ellipse cx="300" cy="255" rx="145" ry="210" fill="none" stroke="#5591c7" />{Array.from({ length: 17 }, (_, i) => <ellipse key={i} cx="300" cy="255" rx={145 - i * 7} ry={210 - i * 9} fill="none" stroke={`rgba(85,145,199,${.15 + i * .025})`} />)}{Array.from({ length: 21 }, (_, i) => <path key={i} d={`M155 ${80 + i * 18} Q300 ${120 + i * 14} 445 ${80 + i * 18}`} fill="none" stroke="rgba(221,105,116,.35)" />)}</svg><div className="absolute left-3 top-3 font-mono text-[10px]">{photo?.id ?? "NO PHOTO"} · {photo?.bucket ?? "—"}</div></div><aside className="space-y-2">{["Mesh 35 709 vertices", "Landmarks 106/134", "Observed UV only", "Heatmap z-score", "Morph A→B"].map(x => <div key={x} className="bg-surface border border-border p-3 font-mono text-[10px]">✓ {x}</div>)}{photo && <><button onClick={() => onInspect(photo)} className="w-full bg-info/20 border border-info/50 p-3 font-mono text-[10px]">РАЗВЕРНУТЬ OVERLAY</button><select value={photo.id} onChange={e => onSelect(e.target.value)} className="w-full bg-surface-2 border border-border p-2 font-mono text-[10px]">{photos.slice(0, 200).map(p => <option key={p.id} value={p.id}>{p.id} · {p.date}</option>)}</select></>}</aside></div></Shell>; }

  if (kind === "DRIFT") return <Shell title="LANDMARK DRIFT" sub="Хронологический дрейф геометрии, распределённый по девяти ракурсам."><div className="grid grid-cols-3 gap-3 mb-4"><MetricCard label="ORBIT DRIFT" value={mean(photos, p => Math.abs(p.zOrbitDepth)).toFixed(2)} note="mean |z|" /><MetricCard label="CHIN DRIFT" value={mean(photos, p => Math.abs(p.zChinProj)).toFixed(2)} note="mean |z|" color="#e8af34" /><MetricCard label="JAW DRIFT" value={mean(photos, p => Math.abs(p.zJawWidth)).toFixed(2)} note="mean |z|" color="#dd6974" /></div><div className="bg-surface border border-border p-4"><Spark values={sampled.map(p => p.zChinProj)} color="#dd6974" height={280} /></div></Shell>;

  if (kind === "METRICS") return <Shell title="МЕТРИКИ И КАЛИБРОВКА" sub="12 независимых каналов; значения требуют quality gate и сравнения внутри одного pose bin."><div className="grid grid-cols-4 gap-3">{[["BONE", mean(photos,p=>p.boneScore)],["ORBITS",mean(photos,p=>p.orbit)],["CHIN",mean(photos,p=>p.chin)],["JAW",mean(photos,p=>p.jaw)],["CHEEK",mean(photos,p=>p.cheek)],["SYMMETRY",mean(photos,p=>p.symmetry)],["LBP",mean(photos,p=>p.lbpEntropy)],["FRANGI",mean(photos,p=>p.frangi)],["WRINKLE",mean(photos,p=>p.wrinkle)],["SUBSURFACE",mean(photos,p=>p.subsurface)],["P(H0)",mean(photos,p=>p.p0)],["QUALITY",mean(photos,p=>p.quality)]].map(([label,value]) => <MetricCard key={label as string} label={label as string} value={(value as number).toFixed(3)} note="медиана текущего фильтра" />)}</div></Shell>;

  const anomalies = photos.filter(anomaly).length;
  return <Shell title="СТАТИСТИКА КОЛЛЕКЦИИ" sub="Исключённые и низкокачественные кадры остаются наблюдаемыми в отчёте."><div className="grid grid-cols-4 gap-3"><MetricCard label="ФОТО" value={String(photos.length)} note="текущая выборка" /><MetricCard label="АНОМАЛЬНЫЕ СИГНАЛЫ" value={String(anomalies)} note={`${((anomalies / Math.max(1, photos.length)) * 100).toFixed(1)}%`} color="#dd6974" /><MetricCard label="СРЕДНЕЕ КАЧЕСТВО" value={mean(photos,p=>p.quality).toFixed(3)} note="quality gate" color="#6daa45" /><MetricCard label="POSE BINS" value="9" note="нормативная схема" /></div><div className="grid grid-cols-3 gap-4 mt-4"><div className="bg-surface border border-border p-4"><h2 className="font-mono text-[10px] mb-3">ГИПОТЕЗЫ</h2>{(["H0","H1","H2"] as const).map(h => { const n=photos.filter(p=>p.dominant===h).length; return <div key={h} className="flex justify-between py-2 border-b border-border"><span style={{color:HYPOTHESIS_COLORS[h]}}>{h}</span><span>{n}</span></div>;})}</div><div className="col-span-2 bg-surface border border-border p-4"><h2 className="font-mono text-[10px] mb-3">EVIDENCE STATES</h2>{Object.entries(FUZZY_COLORS).map(([label,color])=>{const n=photos.filter(p=>p.fuzzy===label).length;return <div key={label} className="grid grid-cols-[180px_1fr_50px] gap-2 items-center py-1"><span className="font-mono text-[9px]">{label}</span><div className="h-2 bg-surface-3"><div className="h-full" style={{width:`${n/Math.max(1,photos.length)*100}%`,background:color}}/></div><span className="font-mono text-[9px] text-right">{n}</span></div>})}</div></div></Shell>;
}
